### ISSUE TITLE
Index Out of Range Error in live-image-classifier

### ISSUE THREAD

**Issue by sidagarwal04** [sidagarwal04/ncappzoo#1]
Error stacktrace below for "../ncappzoo/apps/live-image-classifier":

`Traceback (most recent call last):
  File "live-image-classifier.py", line 186, in <module>
    main()
  File "live-image-classifier.py", line 132, in main
    infer_image( graph, img, frame )
  File "live-image-classifier.py", line 109, in infer_image
    + " ( %.2f ms )" % ( numpy.sum( inference_time ) ) )
IndexError: list index out of range`

**Comment by sidagarwal04** [comment]
@nealvis @ashwinvijayakumar Would like to seek your support to fix this issue.
